---
- name: This sets up an httpd webserver
  hosts: all
  sudo: true
  tasks:
  - name: Install the httpd rpm
    apt: name=apache2
  - name: start the httpd service
    service: name=apache2 state=started
#  - name: Open port 80
#    ufw: service=ufw permanent=true state=enabled
#  - name: start the ufw  service
#    service: name=ufw state=restarted
